/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Work from "../components/Work";
import Testimonial from "../components/Testimonial";
import Footer from "../components/Footer";
import Copyright from "../components/Copyright";

export default function About() {
  return (
    <div>
      <Head>
        <title>About | Vishwajeet Patil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Caudex:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <Navbar tab={"1"} />
        <Footer />
        <Copyright />
      </main>
    </div>
  );
}
